//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_497.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Click_Difference
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
        public Nullable<int> click { get; set; }
    }
}
