//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_497.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feed_back
    {
        public int id { get; set; }
        public string customer_Name { get; set; }
        public string mail { get; set; }
        public string message { get; set; }
    }
}
