//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_497.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities3 : DbContext
    {
        public projectEntities3()
            : base("name=projectEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Product_Sell> Product_Sells { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<SubCategoryID> SubCategoryIDs { get; set; }
        public virtual DbSet<Percentage> Percentages { get; set; }
        public virtual DbSet<Click_Difference> Click_Differences { get; set; }
        public virtual DbSet<feed_back> feed_back { get; set; }
        public virtual DbSet<product> products { get; set; }
    }
}
