//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_497.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Sell
    {
        public int SellProductId { get; set; }
        public Nullable<int> productId { get; set; }
        public string productName { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<System.DateTime> sellStartDate { get; set; }
        public Nullable<System.DateTime> sellEndDate { get; set; }
    }
}
