//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_497.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string image { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> click { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<System.DateTime> sellStartDate { get; set; }
        public Nullable<System.DateTime> sellEndDate { get; set; }
        public string offerImage { get; set; }
        public string offerDetails { get; set; }
        public Nullable<System.DateTime> offerAvailable { get; set; }
        public Nullable<int> Buy { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> January { get; set; }
        public Nullable<int> February { get; set; }
        public Nullable<int> March { get; set; }
        public Nullable<int> April { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> June { get; set; }
        public Nullable<int> July { get; set; }
        public Nullable<int> August { get; set; }
        public Nullable<int> September { get; set; }
        public Nullable<int> October { get; set; }
        public Nullable<int> November { get; set; }
        public Nullable<int> December { get; set; }
        public Nullable<int> PredectionResult { get; set; }
        public Nullable<int> Result { get; set; }
        public Nullable<int> predection { get; set; }
        public Nullable<System.DateTime> clickDate { get; set; }
        public Nullable<int> previous_click { get; set; }
        public Nullable<int> count_improvment { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual category category { get; set; }
        public virtual SubCategoryID SubCategoryID1 { get; set; }
    }
}
